### PR TITLE
Move workflow file into .github/workflows

### PR DESCRIPTION
**Pull request by namirinz**

### CODE REVIEW

**Review by ishiasaka — CHANGES_REQUESTED** [review]
Add script to run test e2e pls.

**Comment by namirinz** [comment]
> Add script to run test e2e pls.

Done

**Comment by namirinz** [comment]
@hirasawaau 
BTW plz fix bug 
```
Cannot find module '@/schema/health.schema' from '../src/health/dto/health.response.dto.ts'
import { HealthClass } from '@/schema/health.schema';
```
in branch refactor/path-reference first. It's trow an error when try to run the e2e test as you can see in the GitHub action.

**Comment by ishiasaka** [comment]
> @hirasawaau BTW plz fix bug
> 
> ```
> Cannot find module '@/schema/health.schema' from '../src/health/dto/health.response.dto.ts'
> import { HealthClass } from '@/schema/health.schema';
> ```
> 
> in branch refactor/path-reference first. It's trow an error when try to run the e2e test as you can see in the GitHub action.

OK It's because jest doesn't read tsconfig.json only, i will fix it

**Review by ishiasaka — APPROVED** [review]
Yatta It's passed.

**Pull request merged**
